# Generated by Django 4.2.1 on 2023-05-16 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skins_tables', '0002_alter_skin_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
