# Generated by Django 4.2.1 on 2023-05-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins_tables', '0003_alter_skin_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='created_date',
            field=models.DateTimeField(blank=True, default=1, null=True),
        ),
    ]
